server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 15000
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 30
    instance-id: ${spring.application.name}:${server.port}