--liquibase formatted sql

--changeset nikolskiy:2022-02-02--0014-create-tables
DROP TABLE IF EXISTS TRANSACTIONS CASCADE;
--changeset nikolskiy:2022-02-02--0015-create-tables
CREATE TABLE TRANSACTIONS
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY,
    tracking_number uuid,
    bank_status varchar(255),
    financial_institution_status varchar(255),
    amount decimal,
    created_dt timestamp,
    currency varchar(255) DEFAULT 'RUB',
    client_id bigint,
    account_sender_id bigint,
    account_receiver_id bigint,
    PRIMARY KEY (id)
);