spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    eviction-interval-timer-in-ms: 15000
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8765

zuul:
  prefix: /api
  routes:
    bank: /bank/**
    financial-institution: /fin/**
    bank-correspodent: /corr/**

logging:
  level:
    root:
      DEBUG