spring:
  application:
    name: financial-institution

  datasource:
    url: jdbc:postgresql://localhost:5432/institution
    driverClassName: org.postgresql.Driver
    username: postgres
    password: {cipher}8f5ae1e3c6e9fd68702b89d6c25295ee77c565fd8a601d8efc4353b6c46b5756

  output:
    ansi:
      enabled: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto:
    show-sql: true

  #  sql:
  #    init:
  #      mode: always

  liquibase:
    enabled: true
    liquibase-schema: public

logging:
  level:
    root:
      ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  version: @project.version@
  author: nsnikolsky
  descriptiion: Bank Actuator

schedule-task:
  transactions:
    financial-institution:
      fixedDelay: 1000